// btdt/js/config-fonts.js
window.BTDT_FONTS = {
  inter: 'Inter',
  merriweather: 'Merriweather',
  nunito: 'Nunito',
  'jetbrains-mono': 'JetBrains Mono',
  'playfair-display': 'Playfair Display',
  'roboto-slab': 'Roboto Slab',
  quicksand: 'Quicksand',
  oswald: 'Oswald',
  montserrat: 'Montserrat',
  poppins: 'Poppins',
  roboto: 'Roboto',
  lora: 'Lora',
  raleway: 'Raleway',
  'fira-sans': 'Fira Sans',
  'dm-sans': 'DM Sans',
  'pt-serif': 'PT Serif',
  neucha: 'Neucha',
  'cabin-sketch': 'Cabin Sketch',
  'alfa-slab-one': 'Alfa Slab One',
  'bebas-neue': 'Bebas Neue',
  'open-sans': 'Open Sans',
  lato: 'Lato',
  'source-sans-pro': 'Source Sans Pro',
  ubuntu: 'Ubuntu',
  'work-sans': 'Work Sans',
  manrope: 'Manrope',
  'josefin-sans': 'Josefin Sans',
  jost: 'Jost',
  outfit: 'Outfit',
  lexend: 'Lexend',
  'crimson-text': 'Crimson Text',
  'eb-garamond': 'EB Garamond',
  'libre-baskerville': 'Libre Baskerville',
  'cormorant-garamond': 'Cormorant Garamond',
  bitter: 'Bitter',
  cardo: 'Cardo',
  spectral: 'Spectral',
  lobster: 'Lobster',
  pacifico: 'Pacifico',
  comfortaa: 'Comfortaa',
  'fredoka-one': 'Fredoka One',
  righteous: 'Righteous',
  'abril-fatface': 'Abril Fatface',
  cinzel: 'Cinzel',
  'kaushan-script': 'Kaushan Script',
  'roboto-mono': 'Roboto Mono',
  'fira-code': 'Fira Code',
  'source-code-pro': 'Source Code Pro',
  'space-mono': 'Space Mono',
  inconsolata: 'Inconsolata',
  syne: 'Syne',
  'space-grotesk': 'Space Grotesk',
  'architects-daughter': 'Architects Daughter'
};
